---
docker:
    external-images:
        docker-in-docker: docker:dind@sha256:04fd1a7a19db9f3d0a9d95ef5ad79db235875a8a73af6850e6c5c22bc84cf862
        hadolint: hadolint/hadolint:latest-alpine@sha256:6c4b7c23f96339489dd35f21a711996d7ce63047467a9a562287748a03ad5242
job-defaults:
    retry:
        max: 2
        when:
        - unknown_failure
        - stale_schedule
        - runner_system_failure
        - stuck_or_timeout_failure
    timeout: 5 minutes
jobgraph: {}
runners:
    aliases:
        images:
            os: linux
            runner-tag: gitlab-org-docker
        misc:
            os: linux
            runner-tag: gitlab-org-docker
        t-linux:
            os: linux
            runner-tag: gitlab-org-docker
