---
stages:
  - decision
  - generated-pipeline


decision:
  artifacts:
    expire_in: 1 year
    paths:
      - artifacts/*
  image: registry.gitlab.com/johanlorenzo/jobgraph/decision@sha256:c81ed6d568400dea4fef59b3febc5f231709e6237e53598a8a96e05826574cb8
  retry:
    max: 2
    when:
      - unknown_failure
      - stale_schedule
      - runner_system_failure
      - stuck_or_timeout_failure
  script:
    # We reinstall jobgraph to use the cloned version instead of the version in the docker image
    - pip install --prefix "/runner/.local" --no-deps --editable "$CI_PROJECT_DIR"
    - >-
      if [[ -n $CI_MERGE_REQUEST_SOURCE_PROJECT_URL ]] && [[ $CI_MERGE_REQUEST_SOURCE_PROJECT_URL != '' ]]; then
        export BASE_REPOSITORY="$CI_MERGE_REQUEST_SOURCE_PROJECT_URL"
      else
        export BASE_REPOSITORY="$CI_PROJECT_URL"
      fi
    - >-
      jobgraph decision
      --base-repository="$BASE_REPOSITORY"
      --head-ref="$CI_COMMIT_BRANCH"
      --head-repository="$CI_PROJECT_URL"
      --head-rev="$CI_COMMIT_SHA"
      --head-tag="$CI_COMMIT_TAG"
      --level='1'
      --message="$CI_COMMIT_MESSAGE"
      --owner="$CI_COMMIT_AUTHOR"
      --pipeline-source="$CI_PIPELINE_SOURCE"
      --project='jobgraph'
      --pushdate='0'
  stage: decision


generated-pipeline:
  stage: generated-pipeline
  trigger:
    include:
      - artifact: artifacts/generated-gitlab-ci.yml
        job: decision
    strategy: depend
