---
stages:
  - decision


decision:
  artifacts:
    expire_in: 1 year
    paths:
      - artifacts/*
  image: python:3.10-alpine@sha256:78604a29496b7a1bd5ea5c985d69a0928db7ea32fcfbf71bbde3e317fdd9ac5e
  retry:
    max: 2
    when:
      - unknown_failure
      - stale_schedule
      - runner_system_failure
      - stuck_or_timeout_failure
  script:
    - apk update && apk add --no-cache --update git
    - pip install --require-hashes --requirement "$CI_PROJECT_DIR/requirements/base.txt"
    - python "$CI_PROJECT_DIR/setup.py" install
    - set -x
    - >-
      if [[ -n $CI_MERGE_REQUEST_SOURCE_PROJECT_URL ]]; then
        export BASE_REPOSITORY="$CI_MERGE_REQUEST_SOURCE_PROJECT_URL"
      else
        export BASE_REPOSITORY="$CI_PROJECT_URL"
      fi
    - >-
      jobgraph decision
      --base-repository="$BASE_REPOSITORY"
      --head-ref="$CI_COMMIT_BRANCH"
      --head-repository="$CI_PROJECT_URL"
      --head-rev="$CI_COMMIT_SHA"
      --head-tag="$CI_COMMIT_TAG"
      --level='1'
      --message="$CI_COMMIT_MESSAGE"
      --owner="$CI_COMMIT_AUTHOR"
      --pipeline-source="$CI_PIPELINE_SOURCE"
      --project='jobgraph'
      --pushdate='0'
  stage: decision
