---
stages:
  - decision
  - generated-pipeline


decision:
  artifacts:
    expire_in: 1 year
    paths:
      - artifacts/*
  image: registry.gitlab.com/johanlorenzo/jobgraph/decision@sha256:1d5ce47fcab749ebe0f8642179d0e4e1acb609c93e826d8ea4b31dd6111d2cec
  retry:
    max: 2
    when:
      - unknown_failure
      - stale_schedule
      - runner_system_failure
      - stuck_or_timeout_failure
  script:
    - pip install --no-deps --editable "$CI_PROJECT_DIR"
    - set -x
    - >-
      if [[ -n $CI_MERGE_REQUEST_SOURCE_PROJECT_URL ]] && [[ $CI_MERGE_REQUEST_SOURCE_PROJECT_URL != '' ]]; then
        export BASE_REPOSITORY="$CI_MERGE_REQUEST_SOURCE_PROJECT_URL"
      else
        export BASE_REPOSITORY="$CI_PROJECT_URL"
      fi
    - >-
      jobgraph decision
      --base-repository="$BASE_REPOSITORY"
      --head-ref="$CI_COMMIT_BRANCH"
      --head-repository="$CI_PROJECT_URL"
      --head-rev="$CI_COMMIT_SHA"
      --head-tag="$CI_COMMIT_TAG"
      --level='1'
      --message="$CI_COMMIT_MESSAGE"
      --owner="$CI_COMMIT_AUTHOR"
      --pipeline-source="$CI_PIPELINE_SOURCE"
      --project='jobgraph'
      --pushdate='0'
  stage: decision


generated-pipeline:
  stage: generated-pipeline
  trigger:
    include:
      - artifact: artifacts/generated-gitlab-ci.yml
        job: decision
    strategy: depend
