---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3.10

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-added-large-files
  - id: check-ast
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable
  - id: check-merge-conflict
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: file-contents-sorter
    files: requirements/base.in|requirements/test.in
    args: [--ignore-case, --unique]
  - id: fix-byte-order-marker
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
- repo: https://github.com/psf/black
  rev: 21.12b0
  hooks:
  - id: black
- repo: https://github.com/asottile/pyupgrade
  rev: v2.31.0
  hooks:
  - id: pyupgrade
    args: [--py310-plus]
- repo: https://github.com/pycqa/isort
  rev: "5.10.1"
  hooks:
  - id: isort
- repo: https://github.com/pycqa/flake8
  rev: "4.0.1"
  hooks:
  - id: flake8
- repo: https://github.com/adrienverge/yamllint
  rev: v1.26.3
  hooks:
  - id: yamllint
    args: [--strict]
- repo: https://github.com/hadolint/hadolint
  rev: v2.8.0
  hooks:
  - id: hadolint
- repo: https://github.com/ikamensh/flynt
  rev: "0.76"
  hooks:
  - id: flynt
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.62.3
  hooks:
  - id: terraform_fmt
  - id: terraform_tflint
  - id: terraform_tfsec
