# yamllint disable rule:line-length
# This file is rendered via JSON-e by
# - hg-push - https://hg.mozilla.org/ci/ci-admin/file/default/build-decision/
# - cron tasks - https://hg.mozilla.org/ci/ci-admin/file/default/build-decision/
---
version: 1
tasks:
    - $if: 'tasks_for in ["hg-push", "cron"]'
      then:
          $let:
              # sometimes the push user is just `ffxbld` or the like, but we want an email-like field..
              ownerEmail: {$if: '"@" in push.owner', then: '${push.owner}', else: '${push.owner}@noreply.mozilla.org'}
              # ensure there's no trailing `/` on the repo URL
              repoUrl: {$if: 'repository.url[-1] == "/"', then: {$eval: 'repository.url[:-1]'}, else: {$eval: 'repository.url'}}
              trustDomain: taskgraph
          in:
              taskId: '${ownTaskId}'
              taskGroupId: '${ownTaskId}'  # same as taskId; this is how automation identifies a decision task
              schedulerId: '${trustDomain}-level-${repository.level}'

              created: {$fromNow: ''}
              deadline: {$fromNow: '1 day'}
              expires: {$fromNow: '1 year'}
              metadata:
                  $merge:
                      - owner: "${ownerEmail}"
                        source: "${repoUrl}/raw-file/${push.revision}/.taskcluster.yml"
                      - $if: 'tasks_for == "hg-push"'
                        then:
                            name: "Decision Task"
                        else:
                            name: "Decision Task for cron job ${cron.job_name}"

              provisionerId: "${trustDomain}-${repository.level}"
              workerType: "decision"

              tags:
                  $if: 'tasks_for == "hg-push"'
                  then:
                      createdForUser: "${ownerEmail}"
                      kind: decision-task
                  else:
                      $if: 'tasks_for == "cron"'
                      then:
                        kind: cron-task

              scopes:
                  $if: 'tasks_for == "hg-push"'
                  then:
                      - 'assume:repo:${repoUrl[8:]}:branch:default'
                  else:
                      - 'assume:repo:${repoUrl[8:]}:cron:${cron.job_name}'

              dependencies: []
              requires: all-completed

              priority:
                  # Most times, there is plenty of worker capacity so everything runs
                  # quickly, but sometimes a storm of action tasks lands.  Then we
                  # want, from highest to lowest:
                  # - cron tasks (time-sensitive) (low)
                  # - decision tasks (minimize user-visible delay) (very-low)
                  # - action tasks (avoid interfering with the other two) (lowest)
                  # SCM levels all use different workerTypes, so there is no need for priority
                  # between levels; "low" is the highest priority available at all levels, and
                  # nothing runs at any higher priority on these workerTypes.
                  $if: "tasks_for == 'cron'"
                  then: low
                  else:
                      $if: "tasks_for == 'hg-push'"
                      then: very-low
                      else: lowest  # tasks_for == 'action'
              retries: 5

              payload:
                  env:
                    TASKGRAPH_BASE_REPOSITORY: '${repoUrl}'
                    TASKGRAPH_HEAD_REPOSITORY: '${repoUrl}'
                    TASKGRAPH_HEAD_REF: '${push.revision}'
                    TASKGRAPH_HEAD_REV: '${push.revision}'
                    TASKGRAPH_REPOSITORY_TYPE: hg
                    REPOSITORIES: {$json: {taskgraph: Taskgraph}}
                    HG_STORE_PATH: /builds/worker/checkouts/hg-store

                  cache:
                      "${trustDomain}-level-${repository.level}-checkouts-sparse-v2": /builds/worker/checkouts

                  features:
                      taskclusterProxy: true
                      chainOfTrust: true

                  image: mozillareleases/taskgraph:decision-cf37a916268ac8d3fead0a9e4c8e1075328c98d65e0b93a9cfbafe7ea2d4ad83@sha256:ed00d6fa2e8265e165f0f842dba1448fee718b9cc3263cdea4f44cbe0e7b9431

                  maxRunTime: 1800

                  command:
                      - run-task
                      - '--taskgraph-checkout=/builds/worker/checkouts/src'
                      - '--'
                      - bash
                      - -cx
                      - $let:
                            extraArgs: {$if: 'tasks_for == "cron"', then: '${cron.quoted_args}', else: ''}
                        in:
                            cd /builds/worker/checkouts/src &&
                            ln -s /builds/worker/artifacts artifacts &&
                            pip3 install --user . &&
                            ~/.local/bin/taskgraph decision
                            --pushlog-id='${push.pushlog_id}'
                            --pushdate='${push.pushdate}'
                            --project='${repository.project}'
                            --owner='${ownerEmail}'
                            --level='${repository.level}'
                            --repository-type=hg
                            --tasks-for='${tasks_for}'
                            --base-repository="${repoUrl}"
                            --head-repository="${repoUrl}"
                            --head-ref="${push.revision}"
                            --head-rev="${push.revision}"
                            ${extraArgs}

                  artifacts:
                      'public':
                          type: 'directory'
                          path: '/builds/worker/artifacts'
                          expires: {$fromNow: '1 year'}
                      'public/docker-contexts':
                          type: 'directory'
                          path: '/builds/worker/checkouts/src/docker-contexts'
                          # This needs to be at least the deadline of the
                          # decision task + the docker-image task deadlines.
                          # It is set to a week to allow for some time for
                          # debugging, but they are not useful long-term.
                          expires: {$fromNow: '7 day'}

              extra:
                  $merge:
                      - $if: 'tasks_for == "cron"'
                        then:
                            cron: {$json: {$eval: 'cron'}}
                      - tasks_for: '${tasks_for}'
