---
trust-domain: taskgraph

index:
    products:
        - taskgraph

taskgraph:
    repositories:
        ci:
            name: Taskgraph

workers:
    aliases:
        images:
            implementation: docker-worker
            os: linux
            worker-type: images
        t-linux:
            implementation: docker-worker
            os: linux
            worker-type: linux
        misc:
            implementation: docker-worker
            os: linux
            worker-type: linux
