---
loader: jobgraph.loader.transform:loader

transforms:
- jobgraph.transforms.reinstall_jobgraph:transforms
- jobgraph.transforms.job:transforms


jobs:
    pages:
        artifacts:
            paths:
            - html/jobgraph
        description: Generate documentation and upload it to https://jobgraph-dev.gitlab.io/jobgraph
        image: {in_tree: python_test}
        optimization:
            skip_unless_changed:
            - "**/*.py"
            - "**/*.md"
        reinstall_jobgraph: true
        runner_alias: t-linux
        script:
        - pdoc3 --html jobgraph
        timeout: 3 minutes
