---
job_defaults:
    optimization:
        skip_unless_changed:
        - "**/Dockerfile"


hadolint:
    description: "Run `hadolint` to validate dockerfiles"
    image: {"docker_image_reference": "<hadolint>"}
    script: hadolint $(find "$JOBGRAPH_ROOT_DIR" -name 'Dockerfile')
