---
job_defaults:
    image: {in_tree: python_test}
    optimization:
        skip_unless_changed:
        - "**/*.yml"


yamllint:
    description: "Run `yamllint` to validate the latest changes"
    script: yamllint "$JOBGRAPH_ROOT_DIR"
