---
docker:
    external_images:
        docker_in_docker: docker:dind@sha256:4e04836731b7100e8bd5e0b35756f53d0b6211ddb3cc7ec326ae3640adcfa004
        hadolint: hadolint/hadolint:latest-alpine@sha256:6c4b7c23f96339489dd35f21a711996d7ce63047467a9a562287748a03ad5242
gitlab:
    project_id: 30264497
    root_url: https://gitlab.com
job_defaults:
    retry:
        max: 2
        when:
        - runner_system_failure
        - stale_schedule
        - stuck_or_timeout_failure
        - unknown_failure
    timeout: 5 minutes
    variables:
        ARTIFACT_DOWNLOAD_ATTEMPTS: 3
        GET_SOURCES_ATTEMPTS: 3
        RESTORE_CACHE_ATTEMPTS: 3
jobgraph: {}
runners:
    aliases:
        images:
            os: linux
            runner_tag: gitlab-org-docker
        misc:
            os: linux
            runner_tag: gitlab-org-docker
        t-linux:
            os: linux
            runner_tag: gitlab-org-docker
