---
docker:
    external-images:
        docker-in-docker: docker:dind@sha256:81e122bb407b639068f161ddb90dd0c0e894b1911b496d114aa83752db7a8a81
        hadolint: hadolint/hadolint:latest-alpine@sha256:6c4b7c23f96339489dd35f21a711996d7ce63047467a9a562287748a03ad5242
job-defaults:
    retry:
        max: 2
        when:
            - unknown_failure
            - stale_schedule
            - runner_system_failure
            - stuck_or_timeout_failure
    timeout: 5 minutes
runners:
    aliases:
        images:
            os: linux
            runner-tag: gitlab-org-docker
        misc:
            os: linux
            runner-tag: gitlab-org-docker
        t-linux:
            os: linux
            runner-tag: gitlab-org-docker
