---
docker:
    external_images:
        docker_in_docker: docker:dind@sha256:3aef73464353f0f03b0c6864ac08e54be759aad336de407e6dfcbc7aa53622a2
        hadolint: hadolint/hadolint:latest-alpine@sha256:ea96feb3ea9036a44f9babd32c949b9fddfaadb049525b2ddb454d48a6a9fb03
        jobgraph: registry.gitlab.com/jobgraph-dev/jobgraph/jobgraph:latest@sha256:7c374702c708cd150d1b0ea7cbd4820d255da76f6dadb168c29ea99e606804ae
        jobgraph_tests: registry.gitlab.com/jobgraph-dev/jobgraph/python_test:latest@sha256:f5abdfb9f7a922bffd5d139d62f1449ec36903d163a9403aa60d8cc25fa12b7d
gitlab:
    project_id: 30264497
    root_url: https://gitlab.com
job_defaults:
    timeout: 5 minutes
jobgraph: {}
runners:
    aliases:
        images:
            runner_tag: gitlab-org-docker
        misc:
            runner_tag: gitlab-org-docker
        t-linux:
            runner_tag: gitlab-org-docker
