---
docker:
    external_images:
        docker_in_docker: docker:dind@sha256:4e04836731b7100e8bd5e0b35756f53d0b6211ddb3cc7ec326ae3640adcfa004
        hadolint: hadolint/hadolint:latest-alpine@sha256:6c4b7c23f96339489dd35f21a711996d7ce63047467a9a562287748a03ad5242
        jobgraph: registry.gitlab.com/jobgraph-dev/jobgraph/jobgraph:latest@sha256:d27ab6c1c4062c6dcde355dabd0d4bbe06c328ff795065175b4300b40ab1d14b
        jobgraph_tests: registry.gitlab.com/jobgraph-dev/jobgraph/python_test:latest@sha256:f5abdfb9f7a922bffd5d139d62f1449ec36903d163a9403aa60d8cc25fa12b7d
gitlab:
    project_id: 30264497
    root_url: https://gitlab.com
job_defaults:
    timeout: 5 minutes
jobgraph: {}
runners:
    aliases:
        images:
            runner_tag: gitlab-org-docker
        misc:
            runner_tag: gitlab-org-docker
        t-linux:
            runner_tag: gitlab-org-docker
