# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---

loader: jobgraph.loader.transform:loader

transforms:
- jobgraph.transforms.docker_in_docker:transforms
- jobgraph.transforms.reinstall_jobgraph:transforms
- jobgraph.transforms.job:transforms

job-defaults:
    # Taken from https://docs.gitlab.com/ee/ci/ssh_keys/#ssh-keys-when-using-the-docker-executor
    before_script:
    - eval $(ssh-agent -s)
    - echo "$JOBGRAPH_SSH_PRIVATE_KEY" | base64 -d | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh


jobs:
    jobgraph-dependencies:
        description: Bump jobgraph dependencies (python packages and docker images)
        image: {in-tree: jobgraph-update}
        reinstall-jobgraph: true
        run-on-pipeline-sources:
        - schedule
        runner-alias: misc
        script: gitlab-ci/scripts/update-dependencies.sh origin update-jobgraph-dependencies
