# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---

loader: jobgraph.loader.transform:loader

transforms:
- jobgraph.transforms.docker_in_docker:transforms
- jobgraph.transforms.reinstall_jobgraph:transforms
- jobgraph.transforms.job:transforms

job_defaults:
    # Taken from https://docs.gitlab.com/ee/ci/ssh_keys/#ssh-keys-when-using-the-docker-executor
    before_script:
    - eval $(ssh-agent -s)
    - echo "$JOBGRAPH_BOT_SSH_PRIVATE_KEY" | base64 -d | tr -d '\r' | ssh-add -


jobs:
    jobgraph_dependencies:
        description: Bump jobgraph dependencies (python packages and docker images)
        image: {in_tree: decision}
        reinstall_jobgraph: true
        # We want to run this job in 2 scenarios:
        #  * when the decision image has changed (which is handled by the "job" transform)
        #  * on a regular schedule to update dependencies periodically
        run_on_pipeline_sources:
        - schedule
        runner_alias: misc
        script: >-
            jobgraph update-dependencies
            --new-merge-request
            --git-committer-name='jobgraph-bot'
            --git-committer-email='10283475-jobgraph-bot@users.noreply.gitlab.com'
